project:
  type: website
  output-dir: docs

website:
  title: "Articles"
  navbar:
    left:
      - text: "aliceheiman.xyz"
        href: https://aliceheiman.xyz
    right:
      - text: "Resources"
        href: resourses.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    font:
      heading: "Cardo"
      base: "Plus Jakarta Sans"



